# https://taskfile.dev

version: '3'

vars: {}

tasks:
  install:
    cmds:
      - go mod tidy
      - go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@v2.5.0
  
  serve:
    deps:
      - install
    cmds:
      - go run app/main.go
  
  default:
    cmds:
      - task serve

  test:unit:
    deps:
      - install
    cmds:
      - go test -v ./tests/unit/...

  test:int:
    deps:
      - install
    cmds:
      - go test -v ./tests/integration/...

  lint:
    cmds:
      - golangci-lint run

  lint:fix:
    cmds:
      - golangci-lint run --fix
      