# https://taskfile.dev

version: '3'

vars: {}

tasks:
  install:
    cmds:
      - go mod tidy
  
  serve:
    deps:
      - install
    cmds:
      - go run app/main.go
  
  default:
    cmds:
      - task serve

  test:unit:
    deps:
      - install
    cmds:
      - go test -v ./tests/unit/...

  test:int:
    deps:
      - install
    cmds:
      - go test -v ./tests/integration/...
      